### ISSUE TITLE
HTTP c2 profile with SSL error 

### ISSUE THREAD

**Issue by Third86** [its-a-feature/Apfell#21]
I'm attempting the following setup:
Apfell-jxa -> port 443 on redirector -> port 9001 Apfell server. 

I've made the following changes to the c2 profile files:
```
config.json
  "AgentMessage": [{
      "urls": ["https://www.exampledomain.com"],

................................
    "port": 9001,
    "key_path": "exampledomain-ssl.key",
    "cert_path": "exampledomain-cert.pem",
    "debug": true
    }
  ],
  "apfellBase": "https://localhost/api/v1.4/agent_message"
}

```
Agent_config.json:
```
  "AgentMessage": [{
      "urls": ["https://www.exampledomain.com"],
```
I also have the same cert (exampledomain-ssl.key, exampledomain-cert.pem) set in __init__.py.

however I am getting the below error when starting the internal HTTP server and executing the payload:
```
Output: [2020-03-13 17:33:05 +0000] [87] [ERROR] Transport closed @ ('x.x.x.x', 41184) and exception experienced during error handling
[2020-03-13 17:33:05 +0000] [87] [ERROR] Transport closed @ ('x.x.x.x.', 41186) and exception experienced during error handling
[2020-03-13 17:33:05 +0000] [87] [ERROR] Transport closed @ ('x.x.x.x', 41188) and exception experienced during error handling
```

any idea what I am missing here or what is causing this? thanks in advance.

**Comment by its-a-feature** [comment]
Yeah, let's track down what's happening. When you start the HTTP profile, what output do you get?
You should see something like:
```
Started with pid: 31...
Output: Opening config and starting instances...
not using SSL for port 9001
[2020-03-13 18:07:42 +0000] [31] [INFO] Goin' Fast @ http://0.0.0.0:9001
```
Except saying that it's successfully using SSL for that port.

**Comment by Third86** [comment]
Appreciate the quick response mate!
When I start the internal server for the HTTP profile I am getting:
```
Messages will disappear when this dialog is closed.
Received Message:
Started with pid: 101...
Output: Opening config and starting instances...
using SSL for port 9001
[2020-03-13 18:43:23 +0000] [101] [INFO] Goin' Fast @ https://0.0.0.0:9001
```

**Comment by its-a-feature** [comment]
Ok, all that looks good. What happens if you do:
`curl -vvv https://www.exampledomain.com/test`?
The output of this should depend on what you have set in the `no_match` section of the `config.json` file:
```
 "no_match": {
      "action": "return_file", <--- this specifies which of the following you do
      "redirect": "http://example.com",
      "proxy_get": {
        "url": "https://www.google.com",
        "status": 200
      },
      "proxy_post": {
        "url": "https://www.example.com",
        "status": 200
      },
      "return_file": {
        "name": "fake.html",
        "status": 404
      }
```

**Comment by Third86** [comment]
The following is the full response:

```
* Rebuilt URL to: https://www.exampledomain.com
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to www.exampledomain.com (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.exampledomain.com
*  start date: Mar  4 19:46:45 2020 GMT
*  expire date: Jun  2 19:46:45 2020 GMT
*  subjectAltName: host "www.exampledomain.com" matched cert's "*.exampledomain.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: www.exampledomain.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Connection: keep-alive
< Keep-Alive: 5
< Server: NetDNA-cache/2.2
< Cache-Control: max-age=0, no-cache
< Pragma: no-cache
< Connection: keep-alive
< Content-Type: application/javascript; charset=utf-8
< Content-Length: 133
< 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page Not Found!</title>
</head>
<body>
```

**Comment by its-a-feature** [comment]
ok, all that's looking good. now when you run the agent, and you look at the `View Stdout/Stderr`, do you only see those closed transports? Or is there any other information being printed to the screen?

**Comment by Third86** [comment]
only:
```
Output: [2020-03-13 19:05:30 +0000] [115] [ERROR] Transport closed @ ('3.11.243.244', 43936) and exception experienced during error handling
[2020-03-13 19:05:31 +0000] [115] [ERROR] Transport closed @ ('3.11.243.244', 43938) and exception experienced during error handling
[2020-03-13 19:05:31 +0000] [115] [ERROR] Transport closed @ ('3.11.243.244', 43940) and exception experienced during error handling
```
However, running the the curl command I got:
```
hit a 'no_match' case
calling create_value for data: <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page Not Found!</title>
</head>
<body>

</body>
</html>
with transforms: []
....
```

Also running the script I an getting this error now:
`execution error: Error on line 70: ReferenceError: Can't find variable: raw_c2_config (-2700)`

**Comment by its-a-feature** [comment]
that's the exact output i would expect from the curl command because that curl to `/test` doesn't match what your server is looking for, so it hits a `no_match` case.

🤔 but, that reference error is odd. when you create your payload, that `raw_c2_config` value should be swapped out with the agent configuration you specified in the UI.

When you run it and get those closed transports, can you run `sudo ./display_output.sh apfell_apfell` and see if there are any errors there?

**Comment by Third86** [comment]
No additional errors once I run the payload, seems like the error is from stopping the HTTP server. 
This is the output:
```
1 +0000] - (sanic.access)[INFO][x.x.x.x:21136]: GET https://y.y.y.y/api/v1.4/c2profiles/parameter_instances  200 35
 [*] Waiting for messages in websocket. To exit press CTRL+C
[2020-03-13 19:20:15 +0000] [1] [ERROR] Exception occurred while handling uri: 'https://y.y.y.y/api/v1.4/c2profiles/HTTP/stop'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/site-packages/sanic_jwt/decorators.py", line 222, in decorated_function
    return await response
  File "/usr/local/lib/python3.6/site-packages/sanic_jwt/decorators.py", line 192, in decorated_function
    response = await response
  File "/Apfell/app/api/c2profiles_api.py", line 352, in stop_c2profile
    return json(await stop_c2profile_func(name))
  File "/usr/local/lib/python3.6/site-packages/sanic/response.py", line 220, in json
    dumps(body, **kwargs),
TypeError: �� is not JSON serializable
[2020-03-13 19:20:15 +0000] - (sanic.access)[INFO][x.x.x.x:21149]: GET https://y.y.y.y/api/v1.4/c2profiles/HTTP/stop  500 144
[2020-03-13 19:20:21 +0000] - (sanic.access)[INFO][x.x.x.x:21158]: GET https://y.y.y.y/api/v1.4/c2profiles/HTTP/start  200 20
[2020-03-13 19:21:52 +0000] - (sanic.access)[INFO][x.x.x.x:21265]: GET https://y.y.y.y/api/v1.4/c2profiles/HTTP/status  200 20
```

**Comment by its-a-feature** [comment]
ah yeah i just pushed a fix for that when you initially opened the issue

**Comment by its-a-feature** [comment]
What if you cut out the redirector and call back directly to apfell on port 9001? And to confirm you are running your apfell web ui on port 443 with those SSL certs right?

**Comment by Third86** [comment]
yes same SSL cert for both.

No errors now showing on server, but when I run the payload I still get the following error:
`execution error: Error on line 70: ReferenceError: Can't find variable: raw_c2_config (-2700)`

**Comment by its-a-feature** [comment]
Can you go to the Payload Management page, click "config" next to your payload, and show that information here?

**Comment by Third86** [comment]
```

Agent JSON Config	{ "GET": { "ServerBody": [ { "function": "base64", "parameters": [] }, { "function": "prepend", "parameters": ["!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(\"jQuery requires a window with a document\");return t(e)}:t(e)}(\"undefined\"!=typeof window?window:this,function(e,t){\"use strict\";var n=[],r=e.document,i=Object.getPrototypeOf,o=n.slice,a=n.concat,s=n.push,u=n.indexOf,l={},c=l.toString,f=l.hasOwnProperty,p=f.toString,d=p.call(Object),h={},g=function e(t){return\"function\"==typeof t&&\"number\"!=typeof t.nodeType},y=function e(t){return null!=t&&t===t.window},v={type:!0,src:!0,noModule:!0};function m(e,t,n){var i,o=(t=t||r).createElement(\"script\");if(o.text=e,n)for(i in v)n[i]&&(o[i]=n[i]);t.head.appendChild(o).parentNode.removeChild(o)}function x(e){return null==e?e+\"\":\"object\"==typeof e||\"function\"==typeof e?l[c.call(e)]||\"object\":typeof e}var b=\"3.3.1\",w=function(e,t){return new w.fn.init(e,t)},T=/^[\\s\\uFEFF\\xA0]+|[\\s\\uFEFF\\xA0]+$/g;w.fn=w.prototype={jquery:\"3.3.1\",constructor:w,length:0,toArray:function(){return o.call(this)},get:function(e){return null==e?o.call(this):e<0?this[e+this.length]:this[e]},pushStack:function(e){var t=w.merge(this.constructor(),e);return t.prevObject=this,t},each:function(e){return w.each(this,e)},map:function(e){return this.pushStack(w.map(this,function(t,n){return e.call(t,n,t)}))},slice:function(){return this.pushStack(o.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(e){var t=this.length,n=+e+(e<0?t:0);return this.pushStack(n>=0&&n<t?[this[n]]:[])},end:function(){return this.prevObject||this.constructor()},push:s,sort:n.sort,splice:n.splice},w.extend=w.fn.extend=function(){var e,t,n,r,i,o,a=arguments[0]||{},s=1,u=arguments.length,l=!1;for(\"boolean\"==typeof a&&(l=a,a=arguments[s]||{},s++),\"object\"==typeof a||g(a)||(a={}),s===u&&(a=this,s--);s<u;s++)if(null!=(e=arguments[s]))for(t in e)n=a[t],a!==(r=e[t])&&(l&&r&&(w.isPlainObject(r)||(i=Array.isArray(r)))?(i?(i=!1,o=n&&Array.isArray(n)?n:[]):o=n&&w.isPlainObject(n)?n:{},a[t]=w.extend(l,o,r)):void 0!==r&&(a[t]=r));return a},w.extend({expando:\"jQuery\"+(\"3.3.1\"+Math.random()).replace(/\\D/g,\"\"),isReady:!0,error:function(e){throw new Error(e)},noop:function(){},isPlainObject:function(e){var t,n;return!(!e||\"[object Object]\"!==c.call(e))&&(!(t=i(e))||\"function\"==typeof(n=f.call(t,\"constructor\")&&t.constructor)&&p.call(n)===d)},isEmptyObject:function(e){var t;for(t in e)return!1;return!0},globalEval:function(e){m(e)},each:function(e,t){var n,r=0;if(C(e)){for(n=e.length;r<n;r++)if(!1===t.call(e[r],r,e[r]))break}else for(r in e)if(!1===t.call(e[r],r,e[r]))break;return e},trim:function(e){return null==e?\"\":(e+\"\").replace(T,\"\")},makeArray:function(e,t){var n=t||[];return null!=e&&(C(Object(e))?w.merge(n,\"string\"==typeof e?[e]:e):s.call(n,e)),n},inArray:function(e,t,n){return null==t?-1:u.call(t,e,n)},merge:function(e,t){for(var n=+t.length,r=0,i=e.length;r<n;r++)e[i++]=t[r];return e.length=i,e},grep:function(e,t,n){for(var r,i=[],o=0,a=e.length,s=!n;o<a;o++)(r=!t(e[o],o))!==s&&i.push(e[o]);return i},map:function(e,t,n){var r,i,o=0,s=[];if(C(e))for(r=e.length;o<r;o++)null!=(i=t(e[o],o,n))&&s.push(i);else for(o in e)null!=(i=t(e[o],o,n))&&s.push(i);return a.apply([],s)},guid:1,support:h}),\"function\"==typeof Symbol&&(w.fn[Symbol.iterator]=n[Symbol.iterator]),w.each(\"Boolean Number String Function Array Date RegExp Object Error Symbol\".split(\" \"),function(e,t){l[\"[object \"+t+\"]\"]=t.toLowerCase()});function C(e){var t=!!e&&\"length\"in e&&e.length,n=x(e);return!g(e)&&!y(e)&&(\"array\"===n||0===t||\"number\"==typeof t&&t>0&&t-1 in e)}var E=function(e){var t,n,r,i,o,a,s,u,l,c,f,p,d,h,g,y,v,m,x,b=\"sizzle\"+1*new Date,w=e.document,T=0,C=0,E=ae(),k=ae(),S=ae(),D=function(e,t){return e===t&&(f=!0),0},N={}.hasOwnProperty,A=[],j=A.pop,q=A.push,L=A.push,H=A.slice,O=function(e,t){for(var n=0,r=e.length;n<r;n++)if(e[n]===t)return n;return-1},P=\"\r"] }, { "function": "prepend", "parameters": ["/*! jQuery v3.3.1 | (c) JS Foundation and other contributors | jquery.org/license */"] }, { "function": "append", "parameters": ["\".(o=t.documentElement,Math.max(t.body[\"scroll\"+e],o[\"scroll\"+e],t.body[\"offset\"+e],o[\"offset\"+e],o[\"client\"+e])):void 0===i?w.css(t,n,s):w.style(t,n,i,s)},t,a?i:void 0,a)}})}),w.each(\"blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu\".split(\" \"),function(e,t){w.fn[t]=function(e,n){return arguments.length>0?this.on(t,null,e,n):this.trigger(t)}}),w.fn.extend({hover:function(e,t){return this.mouseenter(e).mouseleave(t||e)}}),w.fn.extend({bind:function(e,t,n){return this.on(e,null,t,n)},unbind:function(e,t){return this.off(e,null,t)},delegate:function(e,t,n,r){return this.on(t,e,n,r)},undelegate:function(e,t,n){return 1===arguments.length?this.off(e,\"**\"):this.off(t,e||\"**\",n)}}),w.proxy=function(e,t){var n,r,i;if(\"string\"==typeof t&&(n=e[t],t=e,e=n),g(e))return r=o.call(arguments,2),i=function(){return e.apply(t||this,r.concat(o.call(arguments)))},i.guid=e.guid=e.guid||w.guid++,i},w.holdReady=function(e){e?w.readyWait++:w.ready(!0)},w.isArray=Array.isArray,w.parseJSON=JSON.parse,w.nodeName=N,w.isFunction=g,w.isWindow=y,w.camelCase=G,w.type=x,w.now=Date.now,w.isNumeric=function(e){var t=w.type(e);return(\"number\"===t||\"string\"===t)&&!isNaN(e-parseFloat(e))},\"function\"==typeof define&&define.amd&&define(\"jquery\",[],function(){return w});var Jt=e.jQuery,Kt=e.$;return w.noConflict=function(t){return e.$===w&&(e.$=Kt),t&&e.jQuery===w&&(e.jQuery=Jt),w},t||(e.jQuery=e.$=w),w});"] } ], "ServerHeaders": { "Server": "NetDNA-cache/2.2", "Cache-Control": "max-age=0, no-cache", "Pragma": "no-cache", "Connection": "keep-alive", "Content-Type": "application/javascript; charset=utf-8" }, "ServerCookies": {}, "AgentMessage": [{ "urls": ["https://www.exampledomain.com:9001/"], "uri": "/<test:string>", "urlFunctions": [ { "name": "<test:string>", "value": "", "transforms": [ { "function": "choose_random", "parameters": ["jquery-3.3.1.min.js","jquery-3.3.1.map"] } ] } ], "AgentHeaders": { "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Host": "code.jquery.com", "Referer": "http://code.jquery.com/", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko" }, "QueryParameters": [ { "name": "q", "value": "message", "transforms": [ ] } ], "Cookies": [ { "name": "__cfduid", "value": "", "transforms": [ { "function": "random_alpha", "parameters": [30] }, { "function": "base64", "parameters": [] } ] } ], "Body": [] }] }, "POST": { "ServerBody": [], "ServerCookies": {}, "ServerHeaders": { "Server": "NetDNA-cache/2.2", "Cache-Control": "max-age=0, no-cache", "Pragma": "no-cache", "Connection": "keep-alive", "Content-Type": "application/javascript; charset=utf-8" }, "AgentMessage": [{ "urls": ["https://www.uslterfinancial.com:9001/"], "uri": "/download.php", "urlFunctions": [], "QueryParameters": [ { "name": "bob2", "value": "justforvalidation", "transforms": [] } ], "AgentHeaders": { "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Host": "code.jquery.com", "Referer": "http://code.jquery.com/", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko" }, "Cookies": [ { "name": "BobCookie", "value": "splat", "transforms": [ { "function": "prepend", "parameters": [ "splatity_" ] } ] } ], "Body": [ { "function": "base64", "parameters": [] }, { "function": "prepend", "parameters": ["<html>"] }, { "function": "append", "parameters": ["</html>"] } ] }] }, "jitter": 50, "interval": 10, "chunk_size": 5120000, "key_exchange": true, "kill_date": "" }
Base64 32byte AES Key	ofuor4/p8A8JakmTuuidRtFfBb6tSeYht/3B6WHHE1s=
```

**Comment by its-a-feature** [comment]
🤔 ok, try creating the payload again. I'm really surprised that you're getting that `raw_c2_config` error since that should be swapped out with that JSON config you just posted. Also make sure your urls don't end with /
```
 "AgentMessage": [{
      "urls": ["http://192.168.205.151:9001"],
      "uri": "/download.php",
```

**Comment by Third86** [comment]
Sadly, same issue. During the creation of the payload, the field "agen json config" is not auto populated, so I am copying the config directly into there. It worked earlier today when I tried the HTTP setup with the redirector. Not sure why this is happening now.

**Comment by its-a-feature** [comment]
Yeah, when creating the payload you have to paste that value in. 

Are you using the latest version of Apfell (1.4)? If so, is this a new install or an upgrade?

In your payload file, on line 27 do you see your agent's UUID stamped in and do you see your base64 AES key in the code?

**Comment by Third86** [comment]
Yes, latest version Apfell (1.4), cloned yesterday as a new install.
UUID is stamped in the payload on line 27. But I don't see the base64 AES key in there.

I am not on the bloodhound slack channel, but will join now.

**Comment by its-a-feature** [comment]
Something turned out to be odd with the hosting box, and rebooting the host machine and starting apfell again seemed to fix the issue.
